apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  namespace: train-model
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        job: model-training-job
    spec:
      serviceAccountName: gitops-job-sa
      restartPolicy: Never
      containers:
        - name: model-trainer
          image: chetanstevesai/kit-trainer:1.0.8
          env:
            - name: JOZU_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jozu-secret
                  key: JOZU_USERNAME
            - name: JOZU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jozu-secret
                  key: JOZU_PASSWORD
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-credentials
                  key: token
            - name: KIT_MODEL_NAME
              value: "modelkit"
            - name: GIT_REPO_URL
              value: "https://github.com/Chetand411/gitops-public.git"
          volumeMounts:
            - name: repo-volume
              mountPath: /workspace  # keep Git repo mounted here
      volumes:
        - name: repo-volume
          gitRepo:
            repository: "https://github.com/Chetand411/gitops-public.git"
            revision: main
